# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Bill.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Bill(object):
    def setupUi(self, Bill):
        Bill.setObjectName("Bill")
        Bill.resize(800, 600)
        font = QtGui.QFont()
        font.setPointSize(11)
        Bill.setFont(font)
        Bill.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton = QtWidgets.QPushButton(Bill)
        self.pushButton.setGeometry(QtCore.QRect(730, 10, 61, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
                                      "border: 2px solid #696969;\n"
                                      "border-radius: 5px;\n"
                                      "}\n"
                                      "QPushButton:hover{\n"
                                      "background-color: #F5F5F5;\n"
                                      "}\n"
                                      "QPushButton:pressed{\n"
                                      "background-color: #696969;\n"
                                      "}")
        self.pushButton.setObjectName("pushButton")
        self.tableWidget = QtWidgets.QTableWidget(Bill)
        self.tableWidget.setGeometry(QtCore.QRect(10, 70, 791, 521))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("QHeaderView::section {\n"
                                       "    background-color:#F5F5F5;\n"
                                       "    border: 1px solid #A9A9A9;\n"
                                       "    border-radius: 4px;\n"
                                       "    font-size: 24px;\n"
                                       "    font-weight: bold;\n"
                                       "}")
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName("tableWidget")
        self.label_2 = QtWidgets.QLabel(Bill)
        self.label_2.setGeometry(QtCore.QRect(110, 30, 61, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Bill)
        self.label_3.setGeometry(QtCore.QRect(340, 30, 61, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(Bill)
        self.lineEdit.setGeometry(QtCore.QRect(410, 20, 121, 41))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
                                    "    border: 2px solid #DCDCDC;\n"
                                    "    border-radius: 5px;\n"
                                    "}\n"
                                    "QLineEdit:hover{\n"
                                    "    border-bottom: 3px solid #708090;\n"
                                    "    }\n"
                                    "QLineEdit:focus{\n"
                                    "    border-bottom: 3px solid #708090;\n"
                                    "    }")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_2 = QtWidgets.QPushButton(Bill)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 10, 71, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
                                        "border: 2px solid #708090;\n"
                                        "border-radius: 10px;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "background-color: #F5F5F5;\n"
                                        "}\n"
                                        "QPushButton:pressed{\n"
                                        "background-color: #708090;\n"
                                        "}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Bill)
        self.pushButton_3.setGeometry(QtCore.QRect(640, 10, 71, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
                                        "border: 2px solid #708090;\n"
                                        "border-radius: 10px;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "background-color: #F5F5F5;\n"
                                        "}\n"
                                        "QPushButton:pressed{\n"
                                        "background-color: #708090;\n"
                                        "}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Bill)
        self.pushButton_4.setGeometry(QtCore.QRect(550, 10, 71, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
                                        "border: 2px solid #708090;\n"
                                        "border-radius: 10px;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "background-color: #F5F5F5;\n"
                                        "}\n"
                                        "QPushButton:pressed{\n"
                                        "background-color: #708090;\n"
                                        "}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(Bill)
        self.lineEdit_2.setGeometry(QtCore.QRect(180, 19, 131, 41))
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
                                      "    border: 2px solid #DCDCDC;\n"
                                      "    border-radius: 5px;\n"
                                      "}\n"
                                      "QLineEdit:hover{\n"
                                      "    border-bottom: 3px solid #708090;\n"
                                      "    }\n"
                                      "QLineEdit:focus{\n"
                                      "    border-bottom: 3px solid #708090;\n"
                                      "    }")
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.retranslateUi(Bill)
        QtCore.QMetaObject.connectSlotsByName(Bill)

    def retranslateUi(self, Bill):
        _translate = QtCore.QCoreApplication.translate
        Bill.setWindowTitle(_translate("Bill", "账单"))
        self.pushButton.setText(_translate("Bill", "返回"))
        self.label_2.setText(_translate("Bill", "日期："))
        self.label_3.setText(_translate("Bill", "分类："))
        self.pushButton_2.setText(_translate("Bill", "查找"))
        self.pushButton_3.setText(_translate("Bill", "保存"))
        self.pushButton_4.setText(_translate("Bill", "删除"))
