# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(600, 450)
        font = QtGui.QFont()
        font.setPointSize(12)
        Login.setFont(font)
        Login.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label = QtWidgets.QLabel(Login)
        self.label.setGeometry(QtCore.QRect(130, 70, 81, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Login)
        self.label_2.setGeometry(QtCore.QRect(130, 180, 81, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Login)
        self.pushButton.setGeometry(QtCore.QRect(120, 290, 151, 81))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
                                      "background-color: rgb(240, 248, 255);\n"
                                      "border-radius: 20px;\n"
                                      "border-bottom: 3px solid #6495ED;\n"
                                      "border-right: 3px solid #6495ED;\n"
                                      "}\n"
                                      "QPushButton:hover{\n"
                                      "    border: none;\n"
                                      "    }")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Login)
        self.pushButton_2.setGeometry(QtCore.QRect(340, 290, 151, 81))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
                                        "background-color: rgb(240, 248, 255);\n"
                                        "border-radius: 20px;\n"
                                        "border-bottom: 3px solid #6495ED;\n"
                                        "border-right: 3px solid #6495ED;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "    border: none;\n"
                                        "    }")
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(Login)
        self.lineEdit.setGeometry(QtCore.QRect(230, 70, 241, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit{\n"
                                    "border:0px;       \n"
                                    "    border-bottom: 4px solid #B3B3B3;     \n"
                                    "}\n"
                                    "QLineEdit:hover{\n"
                                    "    border-bottom: 5px solid #66A3FF;\n"
                                    "    }\n"
                                    "QLineEdit:focus{\n"
                                    "    border-bottom: 5px solid #6495ED;\n"
                                    "    }")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Login)
        self.lineEdit_2.setGeometry(QtCore.QRect(230, 180, 241, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
                                      "border:0px;       \n"
                                      "    border-bottom: 4px solid #B3B3B3;     \n"
                                      "}\n"
                                      "QLineEdit:hover{\n"
                                      "    border-bottom: 5px solid #66A3FF;\n"
                                      "    }\n"
                                      "QLineEdit:focus{\n"
                                      "    border-bottom: 5px solid #6495ED;\n"
                                      "    }")
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "登录"))
        self.label.setText(_translate("Login", "用户名："))
        self.label_2.setText(_translate("Login", "密码："))
        self.pushButton.setText(_translate("Login", "登录"))
        self.pushButton_2.setText(_translate("Login", "注册"))
