# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Statistic.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Statistic(object):
    def setupUi(self, Statistic):
        Statistic.setObjectName("Statistic")
        Statistic.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        Statistic.setFont(font)
        Statistic.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.thisday = QtWidgets.QPushButton(Statistic)
        self.thisday.setGeometry(QtCore.QRect(40, 100, 81, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.thisday.setFont(font)
        self.thisday.setStyleSheet("QPushButton{\n"
                                   "border: 3px solid #708090;\n"
                                   "border-radius: 10px;\n"
                                   "}\n"
                                   "QPushButton:hover{\n"
                                   "background-color: #F5F5F5;\n"
                                   "}\n"
                                   "QPushButton:pressed{\n"
                                   "background-color: #708090;\n"
                                   "}")
        self.thisday.setObjectName("thisday")
        self.thisweek = QtWidgets.QPushButton(Statistic)
        self.thisweek.setGeometry(QtCore.QRect(40, 200, 81, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.thisweek.setFont(font)
        self.thisweek.setStyleSheet("QPushButton{\n"
                                    "border: 3px solid #708090;\n"
                                    "border-radius: 10px;\n"
                                    "}\n"
                                    "QPushButton:hover{\n"
                                    "background-color: #F5F5F5;\n"
                                    "}\n"
                                    "QPushButton:pressed{\n"
                                    "background-color: #708090;\n"
                                    "}")
        self.thisweek.setObjectName("thisweek")
        self.thismonth = QtWidgets.QPushButton(Statistic)
        self.thismonth.setGeometry(QtCore.QRect(40, 300, 81, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.thismonth.setFont(font)
        self.thismonth.setStyleSheet("QPushButton{\n"
                                     "border: 3px solid #708090;\n"
                                     "border-radius: 10px;\n"
                                     "}\n"
                                     "QPushButton:hover{\n"
                                     "background-color: #F5F5F5;\n"
                                     "}\n"
                                     "QPushButton:pressed{\n"
                                     "background-color: #708090;\n"
                                     "}")
        self.thismonth.setObjectName("thismonth")
        self.thisyear = QtWidgets.QPushButton(Statistic)
        self.thisyear.setGeometry(QtCore.QRect(40, 400, 81, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.thisyear.setFont(font)
        self.thisyear.setStyleSheet("QPushButton{\n"
                                    "border: 3px solid #708090;\n"
                                    "border-radius: 10px;\n"
                                    "}\n"
                                    "QPushButton:hover{\n"
                                    "background-color: #F5F5F5;\n"
                                    "}\n"
                                    "QPushButton:pressed{\n"
                                    "background-color: #708090;\n"
                                    "}")
        self.thisyear.setObjectName("thisyear")
        self.total = QtWidgets.QPushButton(Statistic)
        self.total.setGeometry(QtCore.QRect(30, 500, 101, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.total.setFont(font)
        self.total.setStyleSheet("QPushButton{\n"
                                 "border: 3px solid #708090;\n"
                                 "border-radius: 10px;\n"
                                 "}\n"
                                 "QPushButton:hover{\n"
                                 "background-color: #F5F5F5;\n"
                                 "}\n"
                                 "QPushButton:pressed{\n"
                                 "background-color: #708090;\n"
                                 "}")
        self.total.setObjectName("total")
        self.label = QtWidgets.QLabel(Statistic)
        self.label.setGeometry(QtCore.QRect(230, 20, 81, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(Statistic)
        self.textBrowser.setGeometry(QtCore.QRect(330, 30, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("QTextBrowser{\n"
                                       "border-color: #DCDCDC;\n"
                                       "}")
        self.textBrowser.setObjectName("textBrowser")
        self.label_2 = QtWidgets.QLabel(Statistic)
        self.label_2.setGeometry(QtCore.QRect(140, 100, 651, 451))
        self.label_2.setStyleSheet("")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.pushButton_6 = QtWidgets.QPushButton(Statistic)
        self.pushButton_6.setGeometry(QtCore.QRect(710, 20, 71, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton{\n"
                                        "border: 2px solid #696969;\n"
                                        "border-radius: 5px;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "background-color: #F5F5F5;\n"
                                        "}\n"
                                        "QPushButton:pressed{\n"
                                        "background-color: #696969;\n"
                                        "}")
        self.pushButton_6.setObjectName("pushButton_6")

        self.retranslateUi(Statistic)
        QtCore.QMetaObject.connectSlotsByName(Statistic)

    def retranslateUi(self, Statistic):
        _translate = QtCore.QCoreApplication.translate
        Statistic.setWindowTitle(_translate("Statistic", "统计"))
        self.thisday.setText(_translate("Statistic", "今日"))
        self.thisweek.setText(_translate("Statistic", "本周"))
        self.thismonth.setText(_translate("Statistic", "本月"))
        self.thisyear.setText(_translate("Statistic", "本年"))
        self.total.setText(_translate("Statistic", "总支出"))
        self.label.setText(_translate("Statistic", "总计:"))
        self.pushButton_6.setText(_translate("Statistic", "返回"))
